# Generated by Django 5.2.1 on 2025-07-09 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('platform_preferences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_accounts',
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('order', 'Order'), ('complaint', 'Complaint'), ('stock', 'Stock'), ('info', 'Info')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('log_type', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='orders.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_processing_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('zoop', 'Zoop'), ('spicy_wagon', 'Spicy Wagon'), ('yatri_restro', 'Yatri Restro'), ('rajbhog_khana', 'RajBhog Khana')], max_length=50)),
                ('order_id', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_details', models.TextField(blank=True, max_length=100, null=True)),
                ('train_number', models.CharField(blank=True, max_length=20, null=True)),
                ('train_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coach', models.CharField(blank=True, max_length=50, null=True)),
                ('seat', models.CharField(blank=True, max_length=50, null=True)),
                ('pnr', models.CharField(blank=True, max_length=20, null=True)),
                ('train_station', models.TextField(blank=True, null=True)),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('online', 'Online'), ('cod', 'Cash on Delivery'), ('paid_online', 'Paid Online')], max_length=20, null=True)),
                ('item_details', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('undelivered', 'Undelivered')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booked_from', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(default='System', max_length=100)),
                ('email_message_id', models.CharField(max_length=255, unique=True)),
                ('email_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.TextField(blank=True, null=True)),
                ('email_sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('raw_email_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'vendor'], name='orders_user_id_72c714_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['booking_date'], name='orders_booking_fc3e62_idx'), models.Index(fields=['order_id'], name='orders_order_i_88e57b_idx'), models.Index(fields=['email_message_id'], name='orders_email_m_9305f8_idx')],
            },
        ),
    ]
